module.exports = {
  apps: [
    {
      name: 'fastapi-backend',
      script: '/opt/trading-journal/backend/venv/bin/uvicorn',
      args: 'fastapi_app.main:app --port 5000 --host 0.0.0.0 --workers 4',
      cwd: '/opt/trading-journal/backend',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      env: {
        FLASK_ENV: 'production',
      },
      error_file: '/var/log/trading-journal/fastapi-err.log',
      out_file:   '/var/log/trading-journal/fastapi-out.log',
    },
    {
      name: 'celery-worker',
      script: '/opt/trading-journal/backend/venv/bin/celery',
      args: '-A fastapi_app.celery_app worker --loglevel=info',
      cwd: '/opt/trading-journal/backend',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      error_file: '/var/log/trading-journal/celery-err.log',
      out_file:   '/var/log/trading-journal/celery-out.log',
    },
    {
      name: 'nextjs-frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: '/opt/trading-journal/frontend',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      env: {
        PORT: 3000,
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',           // bind to all interfaces; NPM proxies externally
        NEXT_PUBLIC_API_URL: 'https://homma-research.homma.casa/api',
      },
      error_file: '/var/log/trading-journal/nextjs-err.log',
      out_file:   '/var/log/trading-journal/nextjs-out.log',
    },
    {
      name: 'schwab-streamer',
      script: '/opt/trading-journal/backend/venv/bin/python3',
      args: 'momentum_screener/schwab/stream_client.py',
      cwd: '/opt/trading-journal',
      interpreter: 'none',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      error_file: '/var/log/trading-journal/streamer-err.log',
      out_file:   '/var/log/trading-journal/streamer-out.log',
    },
  ],
};
